# @@@@@@@@@  &@@@@@@@@#   (@@@.     @@@@    %@@@& &@@@@    /@@@,     *@@@@@@@@@      @@@@@      @@@@@      #@@@@, .@@@#  @@@&     @@@@*   .@@@@
# @@@@.      &@@@***@@@@/ (@@@.      @@@@  &@@@,  &@@@@@*  /@@@,     *@@@/          @@@@@@&     @@@@@@    (@@@@@, .@@@(  @@@&      #@@@# ,@@@&
# @@@@@@@@%  &@@@   %@@@* (@@@.       %@@@@@@@    &@@@@@@@ /@@@,     *@@@@@@@#     @@@% @@@%    @@@@@@@  /@@@@@@, .@@@(  @@@&       .@@@@@@@*
# @@@@%%%%/  &@@@@@@@@,   (@@@.        ,@@@@@     &@@@ .@@@@@@@,     *@@@&&&&(    @@@@  .@@@(   @@@@,@@@*@@&/@@@, .@@@(  @@@&         @@@@@
# @@@@.....  &@@@ ,@@@@   (@@@,         &@@@      &@@@   %@@@@@,     *@@@*       @@@@@@@@@@@@*  @@@@ (@@@@@ /@@@, .@@@(  @@@&         .@@@(
# @@@@@@@@@  &@@@   @@@@. (@@@@@@@%     &@@@      &@@@     @@@@,     *@@@*      @@@@      &@@@. @@@@  %@@@  /@@@, .@@@(  @@@@@@@@     .@@@(

# Version BETA 1.1.0, Développé par !ldx

# ==============================================================
# ==============================================================

# ==============================================================
# Configuration global
# ==============================================================

# Localisation lors du respawn du joueur
# => "spawn" (spawn) / "" (désactivé)
location_respawn: "spawn"

# Probalilité du drop de la tête d'un joueur tué en PVP
# => Pourcentage (nombre entier compris entre 0 et 100)
probability_drop_death: 10

# Delay par défaut lors des téléportations
teleportation_delay: 5

# ==============================================================
# Messages des événements
# ==============================================================

# Message de bienvenue lors de la première connexion du joueur
# => Message (nombre de lignes illimité)
welcome:
  - "&cBienvenue dans la Erlyn Family !"
  - "&cNous sommes heureux de te compter parmis nous."
  - "&cBonne aventure à toi <3"

# Message lors de la connexion d'un joueur sur le serveur
# => {PLAYER} (pseudo du joueur)
join_message: "&5{PLAYER} &7a rejoint la partie"

# Message lors de la déconnexion d'un joueur sur le serveur
# => {PLAYER} (pseudo du joueur)
quit_message: "&5{PLAYER} &7a quitté la partie"

# Paterne des messages privés
# => {SENDER} (envoyeur), {RECEIVER} (récepteur), {MESSAGE} (message)
msg_patern_message: "&6{SENDER} &7-> &6{RECEIVER} &7{MESSAGE}"

# Paterne des message dans le chat
# {PLAYER} (joueur), {MESSAGE} (message)
chat_patern_message: "&6{PLAYER} &7{MESSAGE}"

# Message lors d'un kill
# {PLAYER} (joueur), {KILLED} (tué), {WEAPON} (arme)
kill_message: "&c{PLAYER} &7a tué &c{KILLED} &7avec un(e) &c{WEAPON}"

# Messages lor sde la mort d'un joueur
# {PLAYER} (joueur)
death_messages:
  - "&4Oups... {PLAYER} est mort !"
  - "&4Une minute de silence pour {PLAYER}"
  - "&4Toute mes condoléances à la famille de {PLAYER}"
  - "&4{PLAYER} le but n'est pas mourir le premier !"
  - "&4Encore un {PLAYER} parti trop tôt..."
  - "&4{PLAYER} s'est fait dégommer !"
  - "&4{PLAYER} n'est pas très doué mdr!"


# ==============================================================
# Messages des commandes
# ==============================================================

# Paterne du message d'annonce global
# => {MESSAGE} (message de l'annonce)
annonce_patern_message: "&4/!\\ &c{MESSAGE}"

# Messages lors de la définition du spawn
teleportation_spawn_message_set: "&7Point de téléportation vers le &cspawn &7définie avec succès !"

# Message avant la téléportation au spawn
teleportation_spawn_message_teleport: "&7Téléportation vers le &cspawn&7 en cours..."

# Message lors de l'annulation de la téléportation
teleportation_global_message_playermove: "&7Oups, tu as &cbougé&7, téléportation annulé !"

# Message lors du bon déroulé de la téléportation
teleportation_global_message_done: "&7Téléportation &créussite &7!"

# Message lorsque le joueur execute la commande /dm sans arguments
msg_message_cmd: "&7Tu dois spécifier &cun joueur &7et &cun message &7!"

# Message lorsque le joueur execute la commande /r sans arguments
reply_message_cmd: "&7Tu dois précifier &cun message &7!"

# Message lors de la régénération d'un joueur
# => {SENDER} (envoyeur), {RECEIVER} (récepteur)
kiss_message: "&d{SENDER} &7envoie un bisous à &d{RECEIVER} &7<3"

# Noms des mods du serveur
# en relation avec la liste des liens des wikis des mods
wikis_mods:
  - "AIOT Botania"
  - "Aroma1997's Dimensional World"
  - "Blood Magic"
  - "Dark Utilites"
  - "Environemental Tech"
  - "Ex Compressum"
  - "Extra Planets"
  - "Flux Networks"
  - "Food Expansion"
  - "MRCrayfish's Furniture Mod"
  - "Hunting Dimension"
  - "Immersive Engineering"
  - "Immersive Petroleum"
  - "Tesla Core lib"
  - "Industrial Foregoing"
  - "Mystical Agriculture"
  - "Mystical Agradditions"
  - "HaverstCraft"
  - "Inventory Pets"
  - "Iron Furnaces"
  - "Pickle Tweaks"
  - "Reliquaire"
  - "Roost"
  - "Simply Jetpacks 2"
  - "Tinker"
  - "Waystones"
  - "Woot"
  - "XL Food Mod"
  - "Immersive Intelligence"
  - "Iron Age Furniture"
  - "AbyssalCraft"
  - "Applied Energistics 2"
  - "AE2 Stuff"
  - "Botania"
  - "Aquaculture"
  - "ProjectE"
  - "/dank/null"
  - "Galacticraft"
  - "RFTools"
  - "Mowzie's Mobs"
  - "RFTools Power"
  - "AgriCraft"
  - "Thaumcraft"
  - "EnderIO"
  - "Twilight Forest"
  - "Elevator Mod"
  - "Iron Chests"
  - "Mahou Tsukai"
  - "Storage Drawers"
  - "TorchMaster"
  - "Structurize"
  - "MineColonies"
  - "Blue Skies"

# Liens des wikis des mods du serveur
# en relation avec la liste des noms des mods du serveur
wikis_links:
  - "https://ftb.fandom.com/wiki/AIOT_Botania"
  - "https://ftb.fandom.com/wiki/Aroma1997%27s_Dimensional_World"
  - "https://ftb.fandom.com/wiki/Blood_Magic/fr"
  - "https://ftb.fandom.com/wiki/Dark_Utilities"
  - "https://ftb.fandom.com/wiki/Environmental_Tech"
  - "https://ftb.fandom.com/wiki/Ex_Compressum"
  - "https://ftbwiki.org/Extra_Planets"
  - "https://ftb.fandom.com/wiki/Flux_Networks"
  - "https://www.minecraft-france.fr/mod-food-expansion/"
  - "https://mrcrayfishs-furniture-mod.fandom.com/wiki/MrCrayfish%27s_Furniture_Mod_Wiki"
  - "https://ftb.fandom.com/wiki/Hunting_Dimension_(dimension)"
  - "https://ftb.fandom.com/wiki/Immersive_Engineering"
  - "https://ftb.fandom.com/wiki/Immersive_Petroleum"
  - "https://ftb.fandom.com/wiki/Tesla_Core_Lib"
  - "https://ftb.fandom.com/wiki/Industrial_Foregoing"
  - "https://ftb.fandom.com/wiki/Mystical_Agriculture"
  - "https://ftb.fandom.com/wiki/Mystical_Agradditions#:~:text=Mystical%20Agradditions%20is%20an%20addon,with%20their%20own%20unique%20modifiers."
  - "https://harvestcraftmod.fandom.com/wiki/HarvestCraft_Wiki"
  - "https://inventory-pets.fandom.com/wiki/Inventory_Pets_Wiki"
  - "https://ftbwiki.org/Iron_Furnace_(Better_Furnaces)"
  - "https://www.9minecraft.net/pickle-tweaks-mod/"
  - "https://ftb.fandom.com/wiki/Xeno%27s_Reliquary"
  - "https://ftb.fandom.com/wiki/Roost_(mod)"
  - "https://ftb.fandom.com/wiki/Jetpack_(Simply_Jetpacks)"
  - "https://tinkers-construct.fandom.com/wiki/Tinkers%27_Construct_Wiki"
  - "https://rlcraft.fandom.com/wiki/Waystones#:~:text=Waystones%20is%20a%20mod%20created,interactable%20structures%20in%20the%20world."
  - "https://ftb.fandom.com/wiki/Woot"
  - "https://ftb.fandom.com/wiki/XL_Food_Mod"
  - "https://www.curseforge.com/minecraft/mc-mods/immersive-intelligence"
  - "https://www.9minecraft.net/iron-age-furniture-mod/"
  - "https://abyssalcraft.fandom.com/wiki/AbyssalCraft_Wiki"
  - "https://ftb.fandom.com/wiki/Applied_Energistics_2"
  - "https://ftb.fandom.com/wiki/AE2_Stuff"
  - "https://ftb.fandom.com/wiki/Botania/fr"
  - "https://ftb.fandom.com/wiki/Aquaculture_2"
  - "https://ftb.fandom.com/wiki/ProjectE"
  - "https://ftb.fandom.com/wiki//dank/null"
  - "https://wiki.micdoodle8.com/wiki/Galacticraft"
  - "https://ftb.fandom.com/wiki/RFTools"
  - "https://mowziesmobs.fandom.com/wiki/Mowzie%27s_Mobs_Wiki"
  - "https://ftb.fandom.com/wiki/RFTools"
  - "https://ftb.fandom.com/wiki/AgriCraft"
  - "https://thaumcraft-4.fandom.com/fr/wiki/Wiki_Thaumcraft_4.2"
  - "https://ftb.fandom.com/wiki/Ender_IO"
  - "https://ftb.fandom.com/wiki/Twilight_Forest/fr"
  - "https://ftb.fandom.com/wiki/Elevator_(Elevator_Mod)"
  - "https://ftb.fandom.com/wiki/Iron_Chests"
  - "https://www.minecraft-france.fr/mod-mahou-tsukai/"
  - "https://ftb.fandom.com/wiki/Storage_Drawers"
  - "https://www.minecraft-france.fr/mod-torchmaster/"
  - "https://www.curseforge.com/minecraft/mc-mods/structurize"
  - "https://wiki.minecolonies.ldtteam.com/"
  - "https://blue-skies.fandom.com/wiki/Blue_Skies_Wiki"

# ==============================================================
# Messages d'erreurs
# ==============================================================

error_message_sender: "&7Oups, tu n'es pas &cun joueur &7!"
error_message_unexpected: "&7Oups, un &cerreur inattendue &7est arrivée !"
error_message_spawn_notset: "&7Auncun &cspawn &7n'est encore définie !"
error_message_broadcast_length: "&7Tu dois spécifier &cun message &7!"
error_message_playervalid: "&7Tu dois spécifier &cun joueur connecté &7!"
error_message_playerisyou: "&7Tu dois spécifier &cun autre joueur connecté &7!"
error_message_reply_notfound: "&7Personne n'attend de &créponse &7de ta part !"

# ==============================================================
# ==============================================================

# ,@@@@@@@@@.       /@@@@@      /@@@@@@@@@,         @@@@    @@@@      &@@@@@@@@&     ,@@@@/    @@@@(
# .@@@@##@@@@@     *@@@@@@&     /@@@@@@@@@@@*       @@@@    @@@@      %@@@@@@@@@@@@    #@@@@ #@@@@
# .@@@@   &@@@/   .@@@&,@@@%    /@@@#   %@@@(       @@@@    @@@@      %@@@,    *@@@@     @@@@@@@,
# .@@@@@@@@@@,   .@@@@  (@@@(   /@@@@@@@@@@.        &@@@    @@@@      %@@@,     @@@@     *@@@@@#
# .@@@&          @@@@@@@@@@@@*  /@@@# @@@@.                 @@@@      %@@@,   #@@@@,    @@@@%@@@@,
# .@@@@         @@@@      @@@@, /@@@#  @@@@%       *@@@@,   @@@@@@@@# %@@@@@@@@@@(    #@@@@   &@@@@